In [1]:
import pandas as pd
import numpy as np

In [2]:
dict1 = {'b':2,'a':1, 'c':3, 'd':1, 'e':2}
ind = np.argsort(list(dict1.values()))
ind = ind.tolist()
end = []
end.extend([(list(dict1.keys())[i],i) for i in sorted(ind)])
end

[('b', 0), ('a', 1), ('c', 2), ('d', 3), ('e', 4)]

In [3]:
from collections import Counter

list1 = [1,2,2,2,3,4,5,5,5,6,6,6,6,6]
Counter(list1).most_common(3)

[(6, 5), (2, 3), (5, 3)]

In [4]:
from sklearn.preprocessing import scale
x = [10,20,30,40,50]
x = scale(x)
x

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [5]:
from sklearn.preprocessing import StandardScaler
x = [[10,20],[30,40],[50, 60]]
scaler = StandardScaler()
scaler.fit(x)
x2 = scaler.transform(x)
x2

array([[-1.22474487, -1.22474487],
       [ 0.        ,  0.        ],
       [ 1.22474487,  1.22474487]])

In [6]:
scaler.inverse_transform(x2)

array([[10., 20.],
       [30., 40.],
       [50., 60.]])

In [ ]:
def slow_calculation(x):
    print("Multiplying", x, "*", x)
    return x * x

[slow_calculation(i) for i in range(3) if slow_calculation(i) > 0]

In [ ]:
# g = (x**2 for x in range(10))
print(g.__next__())

In [ ]:
import pyautogui, time

pyautogui.moveRel(0, -1) 

In [ ]:
pyautogui.FAILSAFE = False 

while True:
    pyautogui.moveRel(0, 10) 
    time.sleep(60)  
    pyautogui.moveRel(0, -10) 

In [1]:
import ctypes

ctypes.windll.kernel32.SetThreadExecutionState(0x80000002) #this will prevent the screen saver or sleep. 
# ctypes.windll.kernel32.SetThreadExecutionState(0x80000000) #set the setting back to normal

-2147483648